steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','.','-t','us-central1-docker.pkg.dev/$PROJECT_ID/springfield/directory-toolbox']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','us-central1-docker.pkg.dev/$PROJECT_ID/springfield/directory-toolbox']
  - name: 'gcr.io/cloud-builders/gcloud'
    script: |
      gcloud run deploy springfield-toolbox \
      --image us-central1-docker.pkg.dev/$PROJECT_ID/springfield/directory-toolbox:latest \
      --region us-central1 \
      --set-secrets "/app/tools.yaml=springfield-directory-tools:latest" \
      --args="--tools-file=/app/tools.yaml","--address=0.0.0.0","--port=8080" \
      --allow-unauthenticated
options:
  automapSubstitutions: true
logging: CLOUD_LOGGING_ONLY
